### PR TITLE
Puppet-lint cleanup of logging_template code

### PR DESCRIPTION
**Pull request by stuartbfox**

### CODE REVIEW

**Comment by electrical** [comment]
Could you rebase this into a single commit?

Thanks!

**Comment by stuartbfox** [comment]
I have no idea if that worked, git is not being my friend .....

**Comment by electrical** [comment]
Looks like it went a bit wrong :-)
you have now 6 commits instead of 1.
This page helped me out in the past: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
If you want i can make the fix my self.

Cheers.

**Comment by stuartbfox** [comment]
I'll reclone your repo, it's only a single line fix.
The git-foo is not strong in this one :)

**Comment by electrical** [comment]
Hehe no worries. thank you very much for the work you've done!

**Pull request closed without merging**
