### PR TITLE
add systemd support for RHEL 7

### PR DESCRIPTION
**Pull request by yanivpaz**
Change code to include systemd option :

[ 'init','systemd'  ]

### CODE REVIEW

**Comment by electrical** [comment]
Hi,

Thanks for the PR.
It seems time to refactor that services part to better select which service provider is required for which linux distro and version.
I don't think people like to set it manually :-)
Think it makes sense to select systemd if its centos/RHEL 7 and sysv init for the older ones?

**Comment by yanivpaz** [comment]
Hi
Yes i think that the default to el7 should be changed to sysyemd.
Anyway , if someone wants to use initv he can set it in hiera file
Thanks
Yaniv

**Comment by electrical** [comment]
Hi,

I've improved the handling of systemd and distro's that use it via PR https://github.com/elasticsearch/puppet-elasticsearch/pull/258
I hope this will work for you?

**Comment by yanivpaz** [comment]
Thanks alot !!we will test it and update .

**Comment by electrical** [comment]
Thanks! i'll close this PR. if you run into any issues can you open a new issue? thanks!

**Pull request closed without merging**
